# Generated by Django 5.2 on 2025-05-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='subtotal_venta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.IntegerField(),
        ),
    ]
