# Generated by Django 5.2 on 2025-05-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0002_alter_detalle_subtotal_venta_alter_venta_total_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
