# Generated by Django 5.2 on 2025-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0003_alter_venta_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion_despacho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_entrega',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_entrega',
            field=models.CharField(choices=[('retiro', 'Retiro en tienda'), ('despacho', 'Despacho a domicilio')], default='retiro', max_length=10),
        ),
    ]
