# Generated by Django 5.2 on 2025-05-14 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0004_venta_direccion_despacho_venta_estado_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Por entregar'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('pagado', 'Pagado')], default='carrito', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='webpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
