# Generated by Django 5.2 on 2025-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0006_detalle_imagen_producto_detalle_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
