# Generated by Django 5.2 on 2025-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0007_venta_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ultimos_digitos',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
